
export const DEGREE_OPTIONS = [
    "Associate of Arts (AA)",
    "Associate of Science (AS)",
    "Associate of Applied Science (AAS)",
    "Bachelor of Arts (BA)",
    "Bachelor of Science (BS)",
    "Bachelor of Fine Arts (BFA)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Engineering (BEng)",
    "Bachelor of Education (BEd)",
    "Bachelor of Architecture (BArch)",
    "Bachelor of Laws (LLB)",
    "Bachelor of Music (BMus)",
    "Bachelor of Nursing (BN)",
    "Bachelor of Social Work (BSW)",
    "Master of Arts (MA)",
    "Master of Science (MS)",
    "Master of Business Administration (MBA)",
    "Master of Fine Arts (MFA)",
    "Master of Education (MEd)",
    "Master of Engineering (MEng)",
    "Master of Laws (LLM)",
    "Master of Public Administration (MPA)",
    "Master of Public Health (MPH)",
    "Master of Social Work (MSW)",
    "Master of Architecture (MArch)",
    "Master of Divinity (MDiv)",
    "Doctor of Philosophy (PhD)",
    "Doctor of Medicine (MD)",
    "Doctor of Dental Surgery (DDS)",
    "Doctor of Optometry (OD)",
    "Doctor of Pharmacy (PharmD)",
    "Doctor of Veterinary Medicine (DVM)",
    "Doctor of Education (EdD)",
    "Doctor of Law (JD)",
    "Doctor of Business Administration (DBA)",
    "Doctor of Psychology (PsyD)",
    "Doctor of Nursing Practice (DNP)",
    "Certificate",
    "Diploma",
    "High School Diploma / GED",
];

export const DISCIPLINE_OPTIONS = [
    "Accounting",
    "Aerospace Engineering",
    "African American Studies",
    "Agricultural Science",
    "Animal Science",
    "Anthropology",
    "Architecture",
    "Art History",
    "Artificial Intelligence",
    "Astronomy",
    "Biochemistry",
    "Biomedical Engineering",
    "Biotechnology",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Cognitive Science",
    "Communication",
    "Computer Engineering",
    "Computer Science",
    "Criminal Justice",
    "Cybersecurity",
    "Data Science",
    "Dentistry",
    "Design",
    "Early Childhood Education",
    "Economics",
    "Education",
    "Electrical Engineering",
    "English",
    "Environmental Engineering",
    "Environmental Science",
    "Finance",
    "Forensic Science",
    "Game Design",
    "Geography",
    "Geology",
    "Graphic Design",
    "Health Administration",
    "History",
    "Human Resources",
    "Industrial Engineering",
    "Information Systems",
    "Information Technology",
    "Interior Design",
    "International Business",
    "International Relations",
    "Journalism",
    "Kinesiology",
    "Landscape Architecture",
    "Law",
    "Liberal Arts",
    "Linguistics",
    "Management",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Medicine",
    "Microbiology",
    "Music",
    "Neuroscience",
    "Nursing",
    "Nutrition",
    "Pharmacy",
    "Philosophy",
    "Photography",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Public Policy",
    "Real Estate",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Statistics",
    "Supply Chain Management",
    "Theater",
    "Urban Planning",
    "Veterinary Medicine",
    "Web Development",
    "Women's Studies",
];

export const WORK_AUTH_OPTIONS = [
    "US Citizen",
    "US Permanent Resident (Green Card)",
    "H-1B Visa",
    "OPT / STEM OPT",
    "TN Visa",
    "L-1 Visa",
    "O-1 Visa",
    "E-3 Visa (Australia)",
    "Canadian Citizen",
    "EU Citizen",
    "Other Work Authorization",
    "Not Authorized to Work",
];

export const DEGREE_STATUS_OPTIONS = [
    "In Progress",
    "Completed",
    "Not Enrolled",
    "Taking a Break",
];

export const EEO_GENDER_OPTIONS = [
    "Male",
    "Female",
    "Non-binary",
    "Self-describe",
    "Prefer not to say",
];

export const EEO_RACE_OPTIONS = [
    "American Indian or Alaska Native",
    "Asian",
    "Black or African American",
    "Hispanic or Latino",
    "Native Hawaiian or Other Pacific Islander",
    "Two or More Races",
    "White",
    "Prefer not to say",
];

export const EEO_VETERAN_OPTIONS = [
    "I am not a protected veteran",
    "I identify as one or more of the classifications of a protected veteran",
    "I don't wish to answer",
];

export const EEO_DISABILITY_OPTIONS = [
    "Yes, I have a disability",
    "No, I do not have a disability",
    "I don't wish to answer",
];

export const REFERRAL_OPTIONS = [
    "LinkedIn",
    "Indeed",
    "Company Website",
    "Glassdoor",
    "Referral / Employee",
    "Career Fair",
    "University / School",
    "GitHub",
    "Twitter / X",
    "Google",
    "Other",
];

export const MONTHS = [
    { value: "01", label: "Jan" },
    { value: "02", label: "Feb" },
    { value: "03", label: "Mar" },
    { value: "04", label: "Apr" },
    { value: "05", label: "May" },
    { value: "06", label: "Jun" },
    { value: "07", label: "Jul" },
    { value: "08", label: "Aug" },
    { value: "09", label: "Sep" },
    { value: "10", label: "Oct" },
    { value: "11", label: "Nov" },
    { value: "12", label: "Dec" },
];